//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public int HAREKETID { get; set; }
        public Nullable<int> STOCKID { get; set; }
        public Nullable<short> GIRIS { get; set; }
        public Nullable<short> CIKIS { get; set; }
    
        public virtual StocCard StocCard { get; set; }
    }
}
